feat: add timing for results filtering
openedx/edx-search pull request #142
Opened 2023-12-19 15:58 UTC by davidnuon

For KBK-57

Add timing for the results filtering and logs it

2023-12-20 21:25 UTC, ashultz0 commented on search/api.py
> +    track.emit("edx.course.search.executed", {
interesting I hadn't thought of just making another event here but this should work fine

for math convenience it is probably worth repeating the result count out that is in the edx.course.search.results_displayed event

and weirdly neither one includes course_id unless that's picked up by snowflake some other way

2023-12-20 21:28 UTC, schenedx requested changes
See my comments inline.

2023-12-20 21:28 UTC, schenedx commented on search/api.py
> +    processing_time_in_seconds = processing_time['end'] - processing_time['start']
Can we please wrap all these into a separate function? That way, we can add a set of unit test to ensure the calculation and event sending

2023-12-20 21:28 UTC, schenedx commented on search/api.py
> +        "processing_time_in_seconds": processing_time_in_seconds,
I think we should emit not only the time in seconds, but also we should emit the start time and end time of this process.

2023-12-20 21:30 UTC, ashultz0 approved these changes
looks good, a couple of extra fields would I think help in the end

also needs a bump in the version number which is in the weird little edxsearch application, maybe 3.8.0 for a nonbreaking but interesting change

we probably don't want to actually cut and release 3.8.0 until after the break but we can set up for it

2023-12-20 21:31 UTC, ashultz0 commented
oh also you can probably collapse the commits together on/before merge, they don't look super informational

2024-01-04 20:57 UTC, schenedx approved these changes
👍

2024-01-04 21:19 UTC, merged